### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by GuangbaoLuo** [ghm17/LOGODetect#1]
cd ./LOGODetect
source ./Code/calculateLD.txt  
for chr in $(seq 22)
do
	Rscript ./Code/random_vector_generation.R ${chr}
	Rscript ./Code/aggregation.R ${chr}
done

**Comment by ghm17** [comment]
Could you let me know what's the error message?

**Comment by GuangbaoLuo** [comment]
cd LOGODetect
for chr in $(seq 22)
do
Rscript ./Code/random_vector_generation.R ${chr}
done

| | 0%Error in fread(paste0("Data/LD_matrix/chr", ch, "/LD_", 1, "_", 2, ".ld")) :
File 'Data/LD_matrix/chr1/LD_1_2.ld' does not exist or is non-readable. getwd()=='/home/luogb/GWAS/LOGODetect'
Calls: as.matrix -> fread
Execution halted



At 2021-04-10 16:27:14, "ghm17" ***@***.***> wrote:

Could you let me know what's the error message?

**Comment by ghm17** [comment]
You will need to run `source ./Code/calculateLD.txt` first. Specially, you would need to install `plink` (downloaded [here](https://www.cog-genomics.org/plink/1.9)) to calculate LD matrix. And make sure that you have added `plink` to your environment variables. Hope it works.

**Comment by GuangbaoLuo** [comment]
thank you, I will check it later



At 2021-04-11 21:39:44, "ghm17" ***@***.***> wrote:

You will need to run source ./Code/calculateLD.txt first. Specially, you would need to install plink (downloaded here) to calculate LD matrix. And make sure that you have added plink to your environment variables. Hope it works.
