### ISSUE TITLE
A bug!

### ISSUE THREAD

**Issue by kitdzlove** [ghm17/LOGODetect#13]
###############
cd ./LOGODetect
source ./Code/calculateLD.txt  
for chr in $(seq 22)
do
	Rscript ./Code/random_vector_generation.R ${chr}
	Rscript ./Code/aggregation.R ${chr}
done
###############
Hello! When I ran this code, it worked on the first and second chromosomes, but I ran on the third chromosome with a bug as shown in the figure below. And for the fourth and fifth chromosomes also appear the same problem, can you give me some advice?

<img width="1126" alt="微信图片_20210622172847" src="https://user-images.githubusercontent.com/52855963/122900837-9770ee00-d37f-11eb-9046-6d9e6d21bbfc.png">

**Comment by ghm17** [comment]
It seems that line 3 of `calculateLD.txt` (`source Code/calculateLD/calculateLD_chr3.txt` to calculate LD matrix in chr 3) did not function normally and was killed. Therefore when you ran `random_vector_generation.R` for chr 3, the required inputs of LD matrix were missing and the error message popped out. You may rerun line 3-22 of the script `calculateLD.txt` and see if the problem can be solved.

**Comment by kitdzlove** [comment]
> It seems that line 3 of `calculateLD.txt` (`source Code/calculateLD/calculateLD_chr3.txt` to calculate LD matrix in chr 3) did not function normally and was killed. Therefore when you ran `random_vector_generation.R` for chr 3, the required inputs of LD matrix were missing and the error message popped out. You may rerun line 3-22 of the script `calculateLD.txt` and see if the problem can be solved.

Thanked your reply！I will try again！
