### ISSUE TITLE
Error in checkForRemoteErrors(val) : one node produced an error: missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by lalagkaspn** [ghm17/LOGODetect#15]
Hi all,

I am trying to run LOGODetect on a cluster for a single population (EUR). However, when I run the Rscript, I get this error message: "Error in checkForRemoteErrors(val) : one node produced an error: missing value where TRUE/FALSE needed" and I do not understand why. Do you have any thoughts on this? Thank you!

Versions:
R: 4.2.1
snowfall: 1.84.6.2
data.table: 1.14.2
opt.parse: 1.7.3
BEDMatrix: 2.0.3

**Comment by ghm17** [comment]
Could you provide the input data so that I can help to debug? Thank you.

**Comment by lalagkaspn** [comment]
Of course! Please, find attached the two GWAS summary statistics. The
sample sizes are:
1st GWAS: 247173
2nd GWAS: 572738

Both of them are of European descent.

Thank you.

Best,
Panos
 1st_GWAS_LOGODetect.txt
<https://drive.google.com/file/d/15q7COt41zUXaWsYXCoBBO56gf_wWLZQm/view?usp=drive_web>
 2nd_GWAS_LOGODetect.txt
<https://drive.google.com/file/d/17yqT257jqKAmoLoQFd74ii--oEuXa4xz/view?usp=drive_web>


Στις Πέμ 28 Ιουλ 2022 στις 4:04 μ.μ., ο/η ghm17 ***@***.***>
έγραψε:

**Comment by lalagkaspn** [comment]
I finally made it run. One parameter was misspecified in my cluster. Thank you for your time!
