### ISSUE TITLE
The process was killed

### ISSUE THREAD

**Issue by sherryfan030** [ghm17/LOGODetect#16]
Hi, Thank you for providing a great software.

I performed LOGODetect forthe EUR population, but  I get two warning messages:"In normalizePath("~") : path[1]="/sbuild-nonexistent": No such file or directory" and "In searchCommandline(parallel, cpus = cpus, type = type, socketHosts = socketHosts,  :Unknown option on commandline: --file". And finally my process was killed. Any suggestions?

My log file have been uploaded.
[new 1.txt](https://github.com/ghm17/LOGODetect/files/9661686/new.1.txt)

System：Ubuntu 20.04
R: 4.2.1
snowfall: 1.84.6.2
data.table: 1.14.2
opt.parse: 1.7.3
BEDMatrix: 2.0.3

Thanks!

**Comment by ghm17** [comment]
Hi. The software is run parallelly on 20 CPUs by default and requires much memory. I guess it is the insufficient computational resources that cause the cluster to kill the process. You can try adding a flag `--n_cores 2` to see if the error still shows up.
