### ISSUE TITLE
  3 nodes produced errors; first error: 'x' is empty

### ISSUE THREAD

**Issue by AlexYiLuo** [ghm17/LOGODetect#19]
Dear LogoDetect team,

I encountered the following error while running LogoDetect :

Library snowfall loaded.
Library snowfall loaded in cluster.

  3 nodes produced errors; first error: 'x' is empty
Calls: sfLapply ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted

I used the provided 1000G reference and partition file. I can provide the input summary statistics if needed

Thank you very much!

**Comment by ghm17** [comment]
Could you provide me the summary statistics? I can help to find out what's wrong.

**Comment by AlexYiLuo** [comment]
pbc_sub_numge.sumstat
<https://drive.google.com/file/d/1RNURKDb50N5UD3XaMc_5WGdJ_NykUjQw/view?usp=drive_web>
 ssc_sub_numge.sumstat
<https://drive.google.com/file/d/1Sg2HHSMIFXQ__Uovr1HHYSN8XJKbyI9J/view?usp=drive_web>


ghm17 ***@***.***> 于2022年11月17日周四 21:02写道：

**Comment by ghm17** [comment]
Well, I can run logodetect with your summary statistics, and here are the identified regions. [https://drive.google.com/file/d/1Zkpc30C0sP0W2f6UMYPOnwsPcLY6mTrt/view?usp=sharing](url) 
It could be insufficient memory that caused the error. Could you try running with fewer cores or larger memory limit and see if the error still pops out?

**Comment by AlexYiLuo** [comment]
Got you. Thank you so much!!

Yiming
