### ISSUE TITLE
C1L2 column = 0

### ISSUE THREAD

**Issue by gina-parcesepe** [ghm17/LOGODetect#22]
For the "summary of LD scores in /Results/tmp-files/S-LDSC/LOGODetect_theta_0.5_chr1.l2.ldscore.gz" I'm having a column of zeros under the "C1L2".

This is happening for all chromosomes, is there an obvious reason this could be?

<img width="148" alt="LOGODetect issue" src="https://user-images.githubusercontent.com/93779643/211010537-71a0a222-47b0-4639-8bf8-c3ce3f2bc5f4.png">

**Comment by ghm17** [comment]
The reason might be that LOGODetect identify no significant regions for theta=0.5. There were some minor updates for the script a few days ago. Please use the updated tool which skips the step calculating stratified genetic covariance if no region is identified for a given theta.

**Comment by gina-parcesepe** [comment]
This happens for all chromosomes and all theta, but from previous analyses I know that there are regions of correlation.
I'll try re-run with the updated code.
