### ISSUE TITLE
No Output

### ISSUE THREAD

**Issue by NRRdy** [ghm17/LOGODetect#23]
Hello,

I attached a test script I ran using the sample data that came with the installation and following the example outlined in the GitHub (https://github.com/ghm17/LOGODetect#a-concrete-example).

The script appears to have run successfully (see attached log), but in the output folder the program generated a folder called “tmp_files”, but did not generate the desired output (https://github.com/ghm17/LOGODetect#output).

[TestScriptLog.txt](https://github.com/ghm17/LOGODetect/files/11277251/TestScriptLog.txt)

[LogoDetect_TestScript.txt](https://github.com/ghm17/LOGODetect/files/11277233/LogoDetect_TestScript.txt)

Thanks

**Comment by ghm17** [comment]
Yes, the script should run successfully based on the log file. Can you show me what's in the tmp_files so that I can check the script stops in what stage?

**Comment by NRRdy** [comment]
Sure. See attached screen shots.
![ss1](https://user-images.githubusercontent.com/38089663/233212566-381bb515-60a8-4ad3-b30f-abdef1d41718.png)
![ss3](https://user-images.githubusercontent.com/38089663/233212567-c3565730-4e7f-43de-af29-50358396a9e5.png)
![ss2](https://user-images.githubusercontent.com/38089663/233212568-81119468-1de4-49c2-8491-01226d212b25.png)

**Comment by NRRdy** [comment]
Yes, those are all there.

Also:
Qmax_block1...197
ref_bed_block_1...204
ref_bim_block_1...204
sd1_block1...197
sd2_block1...197

**Comment by ghm17** [comment]
Qmax_block should be 1...204 too. Is it possible that your submitted job has been killed due to time limit, and the script has generated files up to 197?

**Comment by NRRdy** [comment]
I am currently in communication with our IT professional who maintains our server, so I have passed along your question and will get back to you.

This is my first time using LOGODetect. How long does it typically take a job to run?

**Comment by ghm17** [comment]
It takes about 15 hours on the example data with 20 cores.

**Comment by ghm17** [comment]
No problem! You can contact me at hmguo@stanford.edu.
