### ISSUE TITLE
Error in unserialize(node$con) : error reading from connection

### ISSUE THREAD

**Issue by Haoxiang-Qi** [ghm17/LOGODetect#25]
I'm sorry to bother you. When I used the LOGO to analysis the same population GWAS summary data, I met a error:

Warning message:
In searchCommandline(parallel, cpus = cpus, type = type, socketHosts = socketHosts,  :
  Unknown option on commandline: --file
Library snowfall loaded.
Library snowfall loaded in cluster.

Error in unserialize(node$con) : error reading from connection
Calls: sfLapply ... FUN -> recvData -> recvData.SOCKnode -> unserialize
Execution halted

the LDSC has been calculated. Can you tell me how to solve this problem? Thanks a lot

**Comment by kruthikaiyer0990** [comment]
Hi! Were you able to solve this?
I'm getting the same error..

```
snowfall 1.84-6.3 initialized (using snow 0.4-4): parallel execution on 25 CPUs.

Warning message:
In searchCommandline(parallel, cpus = cpus, type = type, socketHosts = socketHosts,  :
  Unknown option on commandline: --file
Library snowfall loaded.
Library snowfall loaded in cluster.

Error in unserialize(node$con) : error reading from connection
Calls: sfLapply ... FUN -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
```

**Comment by ghm17** [comment]
Thanks for using our tool! Can you try running with fewer cores, like 5, with argument `--n_cores 5` ?

**Comment by kruthikaiyer0990** [comment]
Hi ! yes it worked with `--n_cores 5` but sometimes it works with `--n_cores 25` too. Any idea why this discrepancy ?

**Comment by ghm17** [comment]
It may happen if memory is out and some parallel jobs have died. You can also try running 25 cores with larger memory. Hope it helps!
