### ISSUE TITLE
Failed to download the reference data

### ISSUE THREAD

**Issue by ggaizz** [ghm17/LOGODetect#28]
I tried to use " wget -O ftp://ftp.biostat.wisc.edu/pub/lu_group/Projects/LOGODetect/LOGODetect_data.tar.gz
 tar -zxvf LOGODetect_1kg_EUR.tar.gz". But it showed "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to ftp.biostat.wisc.edu port 21 after 1 ms: Couldn't connect to server
tar (child): LOGODetect_1kg_EUR.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now" . I want to learn about the reason. Thank you very much!

**Comment by ghm17** [comment]
Thanks for your interest in using our tool! Please try the following command to download the reference dataset:
```
wget -O LOGODetect_data.tar.gz ftp://ftp.biostat.wisc.edu/pub/lu_group/Projects/LOGODetect/LOGODetect_data.tar.gz
tar -zxvf LOGODetect_1kg_EUR.tar.gz
```
I successfully downloaded the data using this command. If it doesn't work for you, please check if your firewall or internet connection might be blocking the download.
