### ISSUE TITLE
Add example output file from tutorial

### ISSUE THREAD

**Issue by jdblischak** [ghm17/LOGODetect#3]
Thanks for creating this useful tool. Would it be possible to share the example output file from the tutorial, `LOGODetect_result.txt`? I am going through the tutorial now, and it would be reassuring to be able to compare the output I generate with the expected results.

And if you don't want to directly commit the output file to the Git repository using Git LFS like you did for the input files, you could alternatively upload it as a release asset to your [1.0.0 release](https://github.com/ghm17/LOGODetect/releases/tag/v1.0.0) (that way the file wouldn't have to be downloaded every time someone clones the repo).

**Comment by ghm17** [comment]
Thank you for the suggestion. We have provided the example output file in `./example/LOGODetect_result.txt`.

**Comment by jdblischak** [comment]
Perfect. Thanks so much for your quick response!
