### ISSUE TITLE
Which sumstats file to pass to LDSC?

### ISSUE THREAD

**Issue by jdblischak** [ghm17/LOGODetect#6]
In [Step 1](https://github.com/ghm17/LOGODetect#step-1-data-preprocessing), the two original sumstats files are preprocessed to create `output_dir/Data_QC/dat1.txt` and `output_dir/Data_QC/dat2.txt` (and the per chromosome files). Then in [Step 2](https://github.com/ghm17/LOGODetect#step-2-use-ldsc-to-calculate-heritability-and-genetic-correlation-of-two-traits), the original sumstats files are passed to the LDSC argument `--sumstats`. Shouldn't the preprocessed sumstats files be passed to LDSC? I realize that in the tutorial example these files are identical (i.e. `preprocess.R` has no effect), but if it did filter some SNPs or flip some alleles and effect sizes, shouldn't they be used?

**Comment by ghm17** [comment]
In practice, LDSC will also preprocess the sumstats files to give reliable heritability and genetic covariance estimates. Therefore, LDSC will give similar results either the original sumstats files or the preprocessed sumstats files are passed to argument `--sumstats`. Yet I agree that it would be more straightforward passing the preprocessed sumstats files to LDSC.
